In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#dataset = pd.read_csv('/Users/aluno/Documents/GitHub/Pos/HXGP/pos-ds-ia-master/aulas/aula_13/train.csv')
dataset = pd.read_csv('c:/Users/Herica/Desktop/Hérica/curso-ia-ciencia_dados/repositorio/GitHub/Pos/HXGP/pos-ds-ia-master/aulas/aula_13/train.csv')

In [ ]:
# visualizar os valores unicos de cada coluna
dataset["MSZoning"].unique()

In [3]:
# Fazer um dicionário da coluna MSZoning
dataset['MSZoning'] = dataset['MSZoning'].map({
    'RL': 1,     'RM': 2,    'FV': 3,     'RH': 4,    'C (all)': 5})

# Substituindo os valores ausentes por zero
dataset['MSZoning'].fillna(0, inplace=True)

In [ ]:
dataset["Street"].unique()

In [4]:
# Fazer um dicionário da coluna Street
dataset['Street'] = dataset['Street'].map({
    'Pave': 1,     'Grvl': 2})
    
# Substituindo os valores ausentes por zero
dataset['Street'].fillna(0, inplace=True)

In [ ]:
dataset["Alley"].unique() #beco

In [5]:
# Fazer um dicionário da coluna Alley
dataset['Alley'] = dataset['Alley'].map({
    'Grvl': 1,    'Pave':2})

# Substituindo os valores ausentes por zero
dataset['Alley'].fillna(0, inplace=True)

In [ ]:
dataset["LotShape"].unique()

In [6]:
# Fazer um dicionário da coluna LotShape
dataset['LotShape'] = dataset['LotShape'].map({
    'Reg': 1,     'IR1': 2,    'IR2':3,    'IR3':4})

# Substituindo os valores ausentes por zero
dataset['LotShape'].fillna(0, inplace=True)

In [ ]:
dataset["SaleCondition"].unique()

In [7]:
# Fazer um dicionário da coluna LotShape
dataset['SaleCondition'] = dataset['SaleCondition'].map({
    'Normal': 1,     'Abnorml': 2,    'Partial':3,    'AdjLand':4,    'Alloca':5,    'Family':6})

# Substituindo os valores ausentes por zero
dataset['SaleCondition'].fillna(0, inplace=True)

In [ ]:
dataset["LandContour"].unique()

In [8]:
# Fazer um dicionário da coluna LotShape
dataset['LandContour'] = dataset['LandContour'].map({
    'Lvl': 1, 'Bnk': 2, 'Low':3,  'HLS':4})

# Substituindo os valores ausentes por zero
dataset['LandContour'].fillna(0, inplace=True)

In [ ]:
dataset["Utilities"].unique()

In [9]:
# Fazer um dicionário da coluna Utilities
dataset['Utilities'] = dataset['Utilities'].map({
    'AllPub': 1,     'NoSeWa': 2})

# Substituindo os valores ausentes por zero
dataset['Utilities'].fillna(0, inplace=True)

In [ ]:
dataset["PoolQC"].unique()

In [10]:
# Fazer um dicionário da coluna PoolQC
dataset['PoolQC'] = dataset['PoolQC'].map({
    'Ex': 1,    'Fa':2,    'Gd':3})

# Substituindo os valores ausentes por zero
dataset['PoolQC'].fillna(0, inplace=True)

In [ ]:
dataset["Fence"].unique()   # cerca

In [11]:
# Fazer um dicionário da coluna Fence
dataset['Fence'] = dataset['Fence'].map({
    'MnPrv': 1,    'GdWo':2,    'GdPrv':3,    'MnWw':4})

# Substituindo os valores ausentes por zero
dataset['Fence'].fillna(0, inplace=True)

In [ ]:
dataset["LotConfig"].unique()

In [12]:
# Fazer um dicionário
dataset['LotConfig'] = dataset['LotConfig'].map({
    'Inside':1,     'FR2': 2,     'Corner': 3,     'CulDSac': 4,     'FR3':5})
    
# Substituindo os valores ausentes por zero
dataset['LotConfig'].fillna(0, inplace=True)

In [83]:
dataset["LandSlope"].unique() #Inclinação da terra

array([1, 2, 3], dtype=int64)

In [13]:
# Fazer um dicionário
dataset['LandSlope'] = dataset['LandSlope'].map({
    'Gtl':1,    'Mod': 2,     'Sev': 3})

# Substituindo os valores ausentes por zero
dataset['LandSlope'].fillna(0, inplace=True)

In [84]:
dataset["Neighborhood"].unique()

array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
       'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
       'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
       'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
       'Blueste'], dtype=object)

In [14]:
# Fazer um dicionário
dataset['Neighborhood'] = dataset['Neighborhood'].map({
    'CollgCr':1,    'Veenker': 2,     'Crawfor': 3, 
    'NoRidge': 4,     'Mitchel': 5,     'Somerst': 6, 
    'NWAmes': 7,     'OldTown': 8,     'BrkSide': 9, 
    'Sawyer': 10,     'NridgHt': 11,     'NAmes': 12, 
    'SawyerW': 13,     'IDOTRR': 14,     'MeadowV': 15, 
    'Edwards': 16,     'Timber': 17,     'Gilbert': 18, 
    'StoneBr': 19,     'ClearCr': 20,     'NPkVill': 21, 
    'Blmngtn': 22,     'BrDale': 23,     'SWISU': 24, 
    'Blueste': 25})

# Substituindo os valores ausentes por zero
dataset['Neighborhood'].fillna(0, inplace=True)

In [89]:
dataset["Condition1"].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [15]:
# Fazer um dicionário
dataset['Condition1'] = dataset['Condition1'].map({
    'Norm': 1,     'Feedr': 2,     'PosN': 3,     'Artery': 4,     'RRAe': 5, 
    'RRNn': 6,     'RRAn': 7,     'PosA': 8,    'RRNe': 9})

# Substituindo os valores ausentes por zero
dataset['Condition1'].fillna(0, inplace=True)

In [92]:
dataset["Condition2"].unique()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [16]:
# Fazer um dicionário
dataset['Condition2'] = dataset['Condition2'].map({
    'Norm': 1,     'Artery': 2,     'RRNn': 3,     'Feedr': 4,     'PosN': 5,     'PosA': 6,     'RRAn': 7,     'RRAe': 8})

# Substituindo os valores ausentes por zero
dataset['Condition2'].fillna(0, inplace=True)

In [95]:
dataset["BldgType"].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [17]:
# Fazer um dicionário
dataset['BldgType'] = dataset['BldgType'].map({
    '1Fam': 1,    '2fmCon': 2,     'Duplex': 3,     'TwnhsE': 4,     'Twnhs': 5})

# Substituindo os valores ausentes por zero
dataset['BldgType'].fillna(0, inplace=True)

In [98]:
dataset["HouseStyle"].unique()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [18]:
# Fazer um dicionário
dataset['HouseStyle'] = dataset['HouseStyle'].map({
    '2Story': 1,    '1Story': 2,     '1.5Fin': 3,     '1.5Unf': 4, 
    'SFoyer': 5,     'SLvl': 6,     '2.5Unf': 7,    '2.5Fin': 8})

# Substituindo os valores ausentes por zero
dataset['HouseStyle'].fillna(0, inplace=True)

In [101]:
dataset["RoofStyle"].unique()


array([1, 2, 3, 4, 5, 6], dtype=int64)

In [19]:
# Fazer um dicionário
dataset['RoofStyle'] = dataset['RoofStyle'].map({
    'Gable': 1,     'Hip': 2,     'Gambrel': 3, 
    'Mansard': 4,     'Flat': 5,     'Shed': 6})

# Substituindo os valores ausentes por zero
dataset['RoofStyle'].fillna(0, inplace=True)

In [102]:
dataset["RoofMatl"].unique()

array(['CompShg', 'WdShngl', 'Metal', 'WdShake', 'Membran', 'Tar&Grv',
       'Roll', 'ClyTile'], dtype=object)

In [20]:
# Fazer um dicionário
dataset['RoofMatl'] = dataset['RoofMatl'].map({
    'CompShg': 1,     'WdShngl': 2,     'Metal': 3,     'WdShake': 4, 
    'Membran': 5,     'Tar&Grv': 6,     'Roll': 7,      'ClyTile': 8})

# Substituindo os valores ausentes por zero
dataset['RoofMatl'].fillna(0, inplace=True)

In [106]:
dataset["Exterior1st"].unique()	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [21]:
# Fazer um dicionário
dataset['Exterior1st'] = dataset['Exterior1st'].map({
    'VinylSd': 1,     'MetalSd': 2,     'Wd Sdng': 3,     'HdBoard': 4,     'BrkFace': 5, 
    'WdShing': 6,    'CemntBd': 7,     'Plywood': 8,     'AsbShng': 9,     'Stucco': 10, 
    'BrkComm': 11,     'AsphShn': 12,    'Stone': 13,     'ImStucc': 14,     'CBlock': 15})

# Substituindo os valores ausentes por zero
dataset['Exterior1st'].fillna(0, inplace=True)

In [109]:

dataset["Exterior2nd"].unique()	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

In [22]:
# Fazer um dicionário
dataset['Exterior2nd'] = dataset['Exterior2nd'].map({
    'VinylSd': 1,     'MetalSd': 2,     'Wd Shng': 3,     'HdBoard': 4,     'Plywood': 5, 
    'Wd Sdng': 6,    'CmentBd': 7,     'BrkFace': 8,     'Stucco': 9,     'AsbShng': 10, 
    'Brk Cmn': 11,     'ImStucc': 12,    'AsphShn': 13,     'Stone': 14,     'Other': 15, 
    'CBlock': 16})

# Substituindo os valores ausentes por zero
dataset['Exterior2nd'].fillna(0, inplace=True)

In [112]:

dataset["MasVnrType"].unique()

array([1., 2., 3., 4., 0.])

In [23]:
# Fazer um dicionário
dataset['MasVnrType'] = dataset['MasVnrType'].map({
    'BrkFace': 1, 'None': 2, 'Stone': 3, 'BrkCmn': 4})

# Substituindo os valores ausentes por zero
dataset['MasVnrType'].fillna(0, inplace=True)

In [115]:

dataset["ExterQual"].unique()

array([1, 2, 3, 4], dtype=int64)

In [24]:
# Fazer um dicionário
dataset['ExterQual'] = dataset['ExterQual'].map({
    'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4})

# Substituindo os valores ausentes por zero
dataset['ExterQual'].fillna(0, inplace=True)

In [116]:
	
dataset["ExterCond"].unique()

array(['TA', 'Gd', 'Fa', 'Po', 'Ex'], dtype=object)

In [25]:
# Fazer um dicionário
dataset['ExterCond'] = dataset['ExterCond'].map({
    'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4, 'Ex': 5})

# Substituindo os valores ausentes por zero
dataset['ExterCond'].fillna(0, inplace=True)

In [120]:
	
dataset["Foundation"].unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [26]:
# Fazer um dicionário
dataset['Foundation'] = dataset['Foundation'].map({
    'PConc': 1, 'CBlock': 2, 'BrkTil': 3, 'Wood': 4, 'Slab': 5, 'Stone': 6})

# Substituindo os valores ausentes por zero
dataset['Foundation'].fillna(0, inplace=True)

In [123]:
	
dataset["BsmtQual"].unique()

array([1., 2., 3., 0., 4.])

In [27]:
# Fazer um dicionário
dataset['BsmtQual'] = dataset['BsmtQual'].map({
    'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4})

# Substituindo os valores ausentes por zero
dataset['BsmtQual'].fillna(0, inplace=True)

In [126]:
	
dataset["BsmtCond"].unique()

array([1., 2., 0., 3., 4.])

In [28]:
# Fazer um dicionário
dataset['BsmtCond'] = dataset['BsmtCond'].map({
    'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4})

# Substituindo os valores ausentes por zero
dataset['BsmtCond'].fillna(0, inplace=True)

In [129]:
	
dataset["BsmtExposure"].unique()

array([1., 2., 3., 4., 0.])

In [29]:
# Fazer um dicionário
dataset['BsmtExposure'] = dataset['BsmtExposure'].map({
    'No': 1, 'Gd': 2, 'Mn': 3, 'Av': 4})

# Substituindo os valores ausentes por zero
dataset['BsmtExposure'].fillna(0, inplace=True)

In [132]:
	
dataset["BsmtFinType1"].unique()

array([1., 2., 3., 4., 5., 0., 6.])

In [30]:
# Fazer um dicionário
dataset['BsmtFinType1'] = dataset['BsmtFinType1'].map({
    'GLQ': 1, 'ALQ': 2, 'Unf': 3, 'Rec': 4, 'BLQ': 5, 'LwQ': 6})

# Substituindo os valores ausentes por zero
dataset['BsmtFinType1'].fillna(0, inplace=True)

In [135]:

dataset["BsmtFinType2"].unique()

array([1., 2., 0., 3., 4., 5., 6.])

In [31]:
# Fazer um dicionário
dataset['BsmtFinType2'] = dataset['BsmtFinType2'].map({
    'Unf': 1, 'BLQ': 2, 'ALQ': 3, 'Rec': 4, 'LwQ': 5, 'GLQ': 6})

# Substituindo os valores ausentes por zero
dataset['BsmtFinType2'].fillna(0, inplace=True)

In [138]:

dataset["Electrical"].unique()

array([1., 2., 3., 4., 5., 0.])

In [32]:
# Fazer um dicionário
dataset['Electrical'] = dataset['Electrical'].map({
    'SBrkr': 1, 'FuseF': 2, 'FuseA': 3, 'FuseP': 4, 'Mix': 5})

# Substituindo os valores ausentes por zero
dataset['Electrical'].fillna(0, inplace=True)

In [141]:

dataset["KitchenQual"].unique()

array([1, 2, 3, 4], dtype=int64)

In [33]:
# Fazer um dicionário
dataset['KitchenQual'] = dataset['KitchenQual'].map({
    'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4})

# Substituindo os valores ausentes por zero
dataset['KitchenQual'].fillna(0, inplace=True)

In [144]:

dataset["Functional"].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [34]:
# Fazer um dicionário
dataset['Functional'] = dataset['Functional'].map({
    'Typ': 1, 'Min1': 2, 'Maj1': 3, 'Min2': 4, 'Mod': 5, 'Maj2': 6, 'Sev': 7})

# Substituindo os valores ausentes por zero
dataset['Functional'].fillna(0, inplace=True)

In [147]:

dataset["FireplaceQu"].unique()

array([0., 1., 2., 3., 4., 5.])

In [34]:
# Fazer um dicionário
dataset['FireplaceQu'] = dataset['FireplaceQu'].map({
    'TA': 1, 'Gd': 2, 'Fa': 3, 'Ex': 4, 'Po': 5})

# Substituindo os valores ausentes por zero
dataset['FireplaceQu'].fillna(0, inplace=True)

In [150]:
dataset["GarageType"].unique()

array([1., 2., 3., 4., 0., 5., 6.])

In [35]:
# Fazer um dicionário
dataset['GarageType'] = dataset['GarageType'].map({
    'Attchd': 1, 'Detchd': 2, 'BuiltIn': 3, 'CarPort': 4, 'Basment': 5, '2Types': 6})

# Substituindo os valores ausentes por zero
dataset['GarageType'].fillna(0, inplace=True)

In [153]:
dataset["GarageFinish"].unique()

array([1., 2., 3., 0.])

In [36]:
# Fazer um dicionário
dataset['GarageFinish'] = dataset['GarageFinish'].map({
    'RFn': 1, 'Unf': 2, 'Fin': 3})

# Substituindo os valores ausentes por zero
dataset['GarageFinish'].fillna(0, inplace=True)

In [156]:
dataset["GarageQual"].unique()

array([1., 2., 3., 0., 4., 5.])

In [37]:
# Fazer um dicionário
dataset['GarageQual'] = dataset['GarageQual'].map({
    'TA': 1, 'Fa': 2, 'Gd': 3, 'Ex': 4, 'Po': 5})

# Substituindo os valores ausentes por zero
dataset['GarageQual'].fillna(0, inplace=True)

In [159]:
dataset["GarageCond"].unique()

array([1., 2., 0., 3., 4., 5.])

In [38]:
# Fazer um dicionário
dataset['GarageCond'] = dataset['GarageCond'].map({
    'TA': 1, 'Fa': 2, 'Gd': 3, 'Po': 4, 'Ex': 5})

# Substituindo os valores ausentes por zero
dataset['GarageCond'].fillna(0, inplace=True)

In [162]:
dataset["PavedDrive"].unique()

array([1, 2, 3], dtype=int64)

In [39]:
# Fazer um dicionário
dataset['PavedDrive'] = dataset['PavedDrive'].map({
    'Y': 1, 'N': 2, 'P': 3})

# Substituindo os valores ausentes por zero
dataset['PavedDrive'].fillna(0, inplace=True)

In [165]:
dataset["MiscFeature"].unique()

array([0., 1., 2., 3., 4.])

In [40]:
# Fazer um dicionário
dataset['MiscFeature'] = dataset['MiscFeature'].map({
    'Shed': 1, 'Gar2': 2, 'Othr': 3, 'TenC': 4})

# Substituindo os valores ausentes por zero
dataset['MiscFeature'].fillna(0, inplace=True)

In [169]:
dataset["CentralAir"].unique()

array([1, 2], dtype=int64)

In [41]:
# Fazer um dicionário
dataset['CentralAir'] = dataset['CentralAir'].map({
    'Y': 1, 'N': 2})

# Substituindo os valores ausentes por zero
dataset['CentralAir'].fillna(0, inplace=True)

In [44]:
dataset["SaleType"].unique()

array(['WD', 'New', 'COD', 'ConLD', 'ConLI', 'CWD', 'ConLw', 'Con', 'Oth'],
      dtype=object)

In [42]:
# Fazer um dicionário
dataset['SaleType'] = dataset['SaleType'].map({
    'WD': 1, 'New': 2, 'COD': 3, 'ConLD': 4, 'ConLI': 5, 'CWD': 6, 'ConLw': 7, 'Con': 8, 'Oth': 9})

# Substituindo os valores ausentes por zero
dataset['SaleType'].fillna(0, inplace=True)

In [52]:
dataset["Heating"].unique()

array(['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'], dtype=object)

In [43]:
# Fazer um dicionário
dataset['Heating'] = dataset['Heating'].map({
    'GasA': 1, 'GasW': 2, 'Grav': 3, 'Wall': 4, 'OthW': 5, 'Floor': 6})

# Substituindo os valores ausentes por zero
dataset['Heating'].fillna(0, inplace=True)

In [54]:
dataset["HeatingQC"].unique()

array(['Ex', 'Gd', 'TA', 'Fa', 'Po'], dtype=object)

In [44]:
# Fazer um dicionário
dataset['HeatingQC'] = dataset['HeatingQC'].map({
    'Ex': 1, 'Gd': 2, 'TA': 3, 'Fa': 4, 'Po': 5})

# Substituindo os valores ausentes por zero
dataset['HeatingQC'].fillna(0, inplace=True)

In [ ]:
#converter todo o dataframe para numero -> não funcionou
#dataset.apply(pd.to_numeric, errors='ignore')

In [ ]:
print (teste)

In [ ]:
dataset.head()

In [ ]:
dataset.dtypes

In [45]:
#criar uma variavel com o target (chamar de y)
y = dataset.SalePrice

In [47]:
y.shape

(1460,)

In [46]:
#dropar (drop) o target (SalePrice) do meu dataset (chamar de X)
dataset.drop(['SalePrice'],axis = 1, inplace = True)

In [48]:
#X = dataset.iloc[:, 1:2].values #pega somente a segunda coluna
#X = dataset.loc[:,['Id', 'MSZoning', 'Street', 'Alley', 'LotShape', 'SaleCondition', 'LandContour', 'Utilities', 'PoolQC', 'Fence']]
X = dataset

In [ ]:
X.head(10)

In [49]:
X.shape

(1460, 80)

In [ ]:
print (X)

In [ ]:
#X = dataset.iloc[:, 1:2].values
#y = dataset.SalePrice

In [ ]:
y.shape

In [ ]:
dataset.shape

In [50]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [51]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X_train,y_train)

ValueError: could not convert string to float: 'Typ'

In [ ]:
pred_teste = linear_reg.predict(X_test)

In [ ]:
pred_train = linear_reg.predict(X_train)

In [ ]:
print(np.mean((y_test - pred_teste) ** 2))

In [ ]:
dataset_teste = pd.read_csv('/Users/Herica/Desktop/Hérica/curso-ia-ciencia_dados/repositorio/GitHub/Pos\/HXGP/pos-ds-ia-master/aulas/aula_13/test.csv')
#dataset_teste.head()


In [ ]:
# Fazer um dicionário da coluna Street
dataset['Street'] = dataset['Street'].map({
    'Pave': 1,     'Grvl': 2})
# Substituindo os valores ausentes por zero
dataset['Street'].fillna(0, inplace=True)



# Fazer um dicionário da coluna Alley
dataset['Alley'] = dataset['Alley'].map({
    'Grvl': 1,    'Pave':2})
# Substituindo os valores ausentes por zero
dataset['Alley'].fillna(0, inplace=True)


# Fazer um dicionário da coluna LotShape
dataset['LotShape'] = dataset['LotShape'].map({
    'Reg': 1,     'IR1': 2,    'IR2':3,    'IR3':4})

# Substituindo os valores ausentes por zero
dataset['LotShape'].fillna(0, inplace=True)


# Fazer um dicionário da coluna LotShape
dataset['SaleCondition'] = dataset['SaleCondition'].map({
    'Normal': 1,     'Abnorml': 2,    'Partial':3,    'AdjLand':4,    'Alloca':5,    'Family':6})

# Substituindo os valores ausentes por zero
dataset['SaleCondition'].fillna(0, inplace=True)


 	# Fazer um dicionário da coluna LotShape
dataset['LandContour'] = dataset['LandContour'].map({
    'Lvl': 1, 'Bnk': 2, 'Low':3,  'HLS':4})

# Substituindo os valores ausentes por zero
dataset['LandContour'].fillna(0, inplace=True)


# Fazer um dicionário da coluna Utilities
dataset['Utilities'] = dataset['Utilities'].map({
    'AllPub': 1,     'NoSeWa': 2})

# Substituindo os valores ausentes por zero
dataset['Utilities'].fillna(0, inplace=True)


# Fazer um dicionário da coluna PoolQC
dataset['PoolQC'] = dataset['PoolQC'].map({
    'Ex': 1,    'Fa':2,    'Gd':3})

# Substituindo os valores ausentes por zero
dataset['PoolQC'].fillna(0, inplace=True)


# Fazer um dicionário da coluna Fence
dataset['Fence'] = dataset['Fence'].map({
    'MnPrv': 1,    'GdWo':2,    'GdPrv':3,    'MnWw':4})

# Substituindo os valores ausentes por zero
dataset['Fence'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['LotConfig'] = dataset['LotConfig'].map({
    'Inside':1,     'FR2': 2,     'Corner': 3,     'CulDSac': 4,     'FR3':5})
    
# Substituindo os valores ausentes por zero
dataset['LotConfig'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['LandSlope'] = dataset['LandSlope'].map({
    'Gtl':1,    'Mod': 2,     'Sev': 3})

# Substituindo os valores ausentes por zero
dataset['LandSlope'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Neighborhood'] = dataset['Neighborhood'].map({
    'CollgCr':1,    'Veenker': 2,     'Crawfor': 3, 
    'NoRidge': 4,     'Mitchel': 5,     'Somerst': 6, 
    'NWAmes': 7,     'OldTown': 8,     'BrkSide': 9, 
    'Sawyer': 10,     'NridgHt': 11,     'NAmes': 12, 
    'SawyerW': 13,     'IDOTRR': 14,     'MeadowV': 15, 
    'Edwards': 16,     'Timber': 17,     'Gilbert': 18, 
    'StoneBr': 19,     'ClearCr': 20,     'NPkVill': 21, 
    'Blmngtn': 22,     'BrDale': 23,     'SWISU': 24, 
    'Blueste': 25})

# Substituindo os valores ausentes por zero
dataset['Neighborhood'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Condition1'] = dataset['Condition1'].map({
    'Norm': 1,     'Feedr': 2,     'PosN': 3,     'Artery': 4,     'RRAe': 5, 
    'RRNn': 6,     'RRAn': 7,     'PosA': 8,    'RRNe': 9})

# Substituindo os valores ausentes por zero
dataset['Condition1'].fillna(0, inplace=True)

# Fazer um dicionário
dataset['Condition2'] = dataset['Condition2'].map({
    'Norm': 1,     'Artery': 2,     'RRNn': 3,     'Feedr': 4,     'PosN': 5,     'PosA': 6,     'RRAn': 7,     'RRAe': 8})

# Substituindo os valores ausentes por zero
dataset['Condition2'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['BldgType'] = dataset['BldgType'].map({
    '1Fam': 1,    '2fmCon': 2,     'Duplex': 3,     'TwnhsE': 4,     'Twnhs': 5})

# Substituindo os valores ausentes por zero
dataset['BldgType'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['HouseStyle'] = dataset['HouseStyle'].map({
    '2Story': 1,    '1Story': 2,     '1.5Fin': 3,     '1.5Unf': 4, 
    'SFoyer': 5,     'SLvl': 6,     '2.5Unf': 7,    '2.5Fin': 8})

# Substituindo os valores ausentes por zero
dataset['HouseStyle'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['RoofStyle'] = dataset['RoofStyle'].map({
    'Gable': 1,     'Hip': 2,     'Gambrel': 3, 
    'Mansard': 4,     'Flat': 5,     'Shed': 6})

# Substituindo os valores ausentes por zero
dataset['RoofStyle'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['RoofMatl'] = dataset['RoofMatl'].map({
    'CompShg': 1,     'WdShngl': 2,     'Metal': 3,     'WdShake': 4, 
    'Membran': 5,     'Tar&Grv': 6,     'Roll': 7,      'ClyTile': 8})

# Substituindo os valores ausentes por zero
dataset['RoofMatl'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Exterior1st'] = dataset['Exterior1st'].map({
    'VinylSd': 1,     'MetalSd': 2,     'Wd Sdng': 3,     'HdBoard': 4,     'BrkFace': 5, 
    'WdShing': 6,    'CemntBd': 7,     'Plywood': 8,     'AsbShng': 9,     'Stucco': 10, 
    'BrkComm': 11,     'AsphShn': 12,    'Stone': 13,     'ImStucc': 14,     'CBlock': 15})

# Substituindo os valores ausentes por zero
dataset['Exterior1st'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Exterior2nd'] = dataset['Exterior2nd'].map({
    'VinylSd': 1,     'MetalSd': 2,     'Wd Shng': 3,     'HdBoard': 4,     'Plywood': 5, 
    'Wd Sdng': 6,    'CmentBd': 7,     'BrkFace': 8,     'Stucco': 9,     'AsbShng': 10, 
    'Brk Cmn': 11,     'ImStucc': 12,    'AsphShn': 13,     'Stone': 14,     'Other': 15, 
    'CBlock': 16})

# Substituindo os valores ausentes por zero
dataset['Exterior2nd'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['MasVnrType'] = dataset['MasVnrType'].map({
    'BrkFace': 1, 'None': 2, 'Stone': 3, 'BrkCmn': 4})

# Substituindo os valores ausentes por zero
dataset['MasVnrType'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['ExterQual'] = dataset['ExterQual'].map({
    'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4})

# Substituindo os valores ausentes por zero
dataset['ExterQual'].fillna(0, inplace=True)

# Fazer um dicionário
dataset['ExterCond'] = dataset['ExterCond'].map({
    'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4, 'Ex': 5})

# Substituindo os valores ausentes por zero
dataset['ExterCond'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Foundation'] = dataset['Foundation'].map({
    'PConc': 1, 'CBlock': 2, 'BrkTil': 3, 'Wood': 4, 'Slab': 5, 'Stone': 6})

# Substituindo os valores ausentes por zero
dataset['Foundation'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['BsmtQual'] = dataset['BsmtQual'].map({
    'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4})

# Substituindo os valores ausentes por zero
dataset['BsmtQual'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['BsmtCond'] = dataset['BsmtCond'].map({
    'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4})

# Substituindo os valores ausentes por zero
dataset['BsmtCond'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['BsmtExposure'] = dataset['BsmtExposure'].map({
    'No': 1, 'Gd': 2, 'Mn': 3, 'Av': 4})

# Substituindo os valores ausentes por zero
dataset['BsmtExposure'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['BsmtFinType1'] = dataset['BsmtFinType1'].map({
    'GLQ': 1, 'ALQ': 2, 'Unf': 3, 'Rec': 4, 'BLQ': 5, 'LwQ': 6})

# Substituindo os valores ausentes por zero
dataset['BsmtFinType1'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['BsmtFinType2'] = dataset['BsmtFinType2'].map({
    'Unf': 1, 'BLQ': 2, 'ALQ': 3, 'Rec': 4, 'LwQ': 5, 'GLQ': 6})

# Substituindo os valores ausentes por zero
dataset['BsmtFinType2'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Electrical'] = dataset['Electrical'].map({
    'SBrkr': 1, 'FuseF': 2, 'FuseA': 3, 'FuseP': 4, 'Mix': 5})

# Substituindo os valores ausentes por zero
dataset['Electrical'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['KitchenQual'] = dataset['KitchenQual'].map({
    'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4})

# Substituindo os valores ausentes por zero
dataset['KitchenQual'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Functional'] = dataset['Functional'].map({
    'Typ': 1, 'Min1': 2, 'Maj1': 3, 'Min2': 4, 'Mod': 5, 'Maj2': 6, 'Sev': 7})

# Substituindo os valores ausentes por zero
dataset['Functional'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['FireplaceQu'] = dataset['FireplaceQu'].map({
    'TA': 1, 'Gd': 2, 'Fa': 3, 'Ex': 4, 'Po': 5})

# Substituindo os valores ausentes por zero
dataset['FireplaceQu'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['GarageType'] = dataset['GarageType'].map({
    'Attchd': 1, 'Detchd': 2, 'BuiltIn': 3, 'CarPort': 4, 'Basment': 5, '2Types': 6})

# Substituindo os valores ausentes por zero
dataset['GarageType'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['GarageFinish'] = dataset['GarageFinish'].map({
    'RFn': 1, 'Unf': 2, 'Fin': 3})

# Substituindo os valores ausentes por zero
dataset['GarageFinish'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['GarageQual'] = dataset['GarageQual'].map({
    'TA': 1, 'Fa': 2, 'Gd': 3, 'Ex': 4, 'Po': 5})

# Substituindo os valores ausentes por zero
dataset['GarageQual'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['GarageCond'] = dataset['GarageCond'].map({
    'TA': 1, 'Fa': 2, 'Gd': 3, 'Po': 4, 'Ex': 5})

# Substituindo os valores ausentes por zero
dataset['GarageCond'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['PavedDrive'] = dataset['PavedDrive'].map({
    'Y': 1, 'N': 2, 'P': 3})

# Substituindo os valores ausentes por zero
dataset['PavedDrive'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['MiscFeature'] = dataset['MiscFeature'].map({
    'Shed': 1, 'Gar2': 2, 'Othr': 3, 'TenC': 4})

# Substituindo os valores ausentes por zero
dataset['MiscFeature'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['CentralAir'] = dataset['CentralAir'].map({
    'Y': 1, 'N': 2})

# Substituindo os valores ausentes por zero
dataset['CentralAir'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['SaleType'] = dataset['SaleType'].map({
    'WD': 1, 'New': 2, 'COD': 3, 'ConLD': 4, 'ConLI': 5, 'CWD': 6, 'ConLw': 7, 'Con': 8, 'Oth': 9})

# Substituindo os valores ausentes por zero
dataset['SaleType'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['Heating'] = dataset['Heating'].map({
    'GasA': 1, 'GasW': 2, 'Grav': 3, 'Wall': 4, 'OthW': 5, 'Floor': 6})

# Substituindo os valores ausentes por zero
dataset['Heating'].fillna(0, inplace=True)


# Fazer um dicionário
dataset['HeatingQC'] = dataset['HeatingQC'].map({
    'Ex': 1, 'Gd': 2, 'TA': 3, 'Fa': 4, 'Po': 5})

# Substituindo os valores ausentes por zero
dataset['HeatingQC'].fillna(0, inplace=True)


In [ ]:
# Fazer um dicionário da coluna MSZoning
dataset['MSZoning'] = dataset['MSZoning'].map({
    'RL': 1,     'RM': 2,    'FV': 3,     'RH': 4,    'C (all)': 5})

# Substituindo os valores ausentes por zero
dataset['MSZoning'].fillna(0, inplace=True)




In [ ]:
#X2 =  dataset_teste.iloc[:, 1:2].values
X2 = dataset_teste.loc[:,['Id', 'MSZoning', 'Street', 'Alley', 'LotShape', 'SaleCondition', 'LandContour', 'Utilities', 'PoolQC', 'Fence']]


In [ ]:
pred_novas_casas = linear_reg.predict(X2)

In [ ]:
print(pred_novas_casas)

In [ ]:
dataset_teste.head()

In [ ]:
dataset_teste.shape

In [ ]:
pred_novas_casas.shape

In [ ]:
# criar a coluna SalePrice no dataset de teste e preencher com os valores preditos
dataset_teste['SalePrice'] = pred_novas_casas

In [ ]:
dataset_teste.head()

In [ ]:
w = dataset_teste.loc[:,['Id','SalePrice']]

In [ ]:
print (w)

In [ ]:
# gerar o arquivo com o resultado
w.to_csv("predition2.csv",columns=["Id","SalePrice"],index=False)